config/routes.rb
Rails.application.routes.draw do
  resources:tweets
  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message, presence: true
    validates :message, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  def create
    message = params[:tweet][:message]
    tdate = params[:tweet][:tdate]
    @tweet = Tweet.new(message: message, tdate: tdate)
    if @tweet.save
      redirect_to '/'
    else
      render 'new'
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    message = params[:tweet][:message]
    tdate = params[:tweet][:tdate]
    tweet.update(message: message, tdate: tdate)
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id = "container">
      <div id = "header">
        <%= render "header" %>
      </div>
      <div id = "sidebar">
          <%= render "sidebar" %>
      </div>
      <div id = "content">
          　<%= render "content" %>
            <%= yield %>
      </div>
      <div id = "footer">
          <%= render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_content.html.erb
<div id="tab2"><%= link_to "ツイート", root_path %>　　ツイートと返信　　メディア</div><hr>　　　　　

app/views/tweets/_footer.html.erb
<%= link_to "ホーム", root_path %>

app/views/tweets/_form.html.erb
<% if @tweet.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
        <%= @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/tweets/_header.html.erb
<%= image_tag 'tuna.jpg', class: 'head' %>
<div id= "tab">
ツイート　フォロー　フォロワー　いいね　　　　フォロー中
</div>

app/views/tweets/_sidebar.html.erb
<%= image_tag 'kindai2.png' %><br>
<div class="user">
<b>近畿大学</b></b></div>
@kinkidaigakuPR<br><br>
近畿大学のTwitter公式アカウントです。
気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。
マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。
履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。<br>
大阪府東大阪市<br>
<a href="https://www.instagram.com/kindaiuniversity/">instagram.com/kindaiuniversi...</a><br>
2010年12月に登録<br>
<%= link_to "ツイート", new_tweet_path, class: 'btn' %>

app/views/tweets/edit.html.erb
<%= render "form" %>

<%= form_for @tweet, url: {action: :update} do |f|%>
    <div class="bg1"><%= link_to image_tag("back.jpg", :size => '30x30'), root_path %>
    </div>  
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
    <% @tweet.tdate = Time.current %>
    <%= f.hidden_field :tdate %> <br>
<% end %>

app/views/tweets/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>


<% @tweets.each do |tweet|%>
    <p> <div class="tx1">
        <%= tweet.message %></div><br>
        <% t1 = Time.current %>
        <% t2 = tweet.tdate %>
        <% t3 = t1 - t2 %>
        <% t3 = t3.floor(0) %>
        <% if t3 > 3600 * 24 %>
            <% day = t3.div(3600 * 24) %>
            <%= day %>日前
        <% elsif t3 > 3600 %>
            <% hour = t3.div(3600) %>
            <%= hour %>時間前
        <% elsif t3 > 60%>
            <% min = t3.div(60) %>
            <%= min %>分前
        <% else %>
            <%= t3 %>秒前
        <% end %>
        <br>
        <%= link_to '削除', tweet_path(tweet.id), :method => :delete %>
        <%= link_to '表示', tweet_path(tweet.id) %>
        <%= link_to '編集', edit_tweet_path(tweet.id) %>
    </p>
    <hr>
<% end %>

app/views/tweets/new.html.erb
<%= render "form" %>

<%= form_for @tweet, url: {action: :create} do |f|%>
    <div class="bg1"><%= link_to image_tag("back.jpg", :size => '30x30'), root_path%>
    </div>  
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
    <% @tweet.tdate = Time.current %>
    <%= f.hidden_field :tdate %> <br>
<% end %>

app/views/tweets/show.html.erb
<h1>
    <div class="bg1"><%= link_to image_tag("back.jpg", :size => '20x20'), root_path %> ツイート
    </div>    
</h1>
<hr>
<div id="tweet">
<p>
   <%= @tweet.message %>
</p>
</div>